// Region Hierarchy Data
export const regionHierarchy = {
  division: [
    "Pacific Northwest Division",
    "Bay Area Central CA Division",
    "LA CSA Division",
    "Southwest Division",
    "Intermountain",
    "Great Plains Division",
    "Central Division 3",
    "South Division",
    "Central and East Texas Division",
    "East Central Divisional Group 2",
    "Illinois Wisconsin Division",
    "East Central Divisional Group 3",
    "East Central Divisional Group 4",
    "East Central Divisional Group 5",
    "NEMA Divisional Group 5",
    "NEMA Divisional Group 4",
    "East Central Divisional Group 1",
    "NEMA Divisional Group 3",
    "NEMA Divisional Group 2",
    "NEMA Divisional Group 1"
  ],
  divisionalGroup: [
    "Pacific Divisional Group",
    "Central Valley California Divisional Group",
    "Los Angeles CSA Divisional Group",
    "Southwest Divisional Group",
    "Intermountain Divisional Group",
    "Great Plains Divisional Group",
    "Central Divisional Group 3",
    "South Divisional Group",
    "Texas Divisional Group",
    "East Central Divisional Group 2",
    "IL-WI Divisional Group",
    "East Central Divisional Group 3",
    "East Central Divisional Group 4",
    "East Central Divisional Group 5",
    "NEMA Divisional Group 5",
    "NEMA Divisional Group 4",
    "East Central Divisional Group 1",
    "NEMA Divisional Group 3",
    "NEMA Divisional Group 2",
    "NEMA Divisional Group 1"
  ],
  msa: [
    "Seattle-Tacoma-Bellevue, WA",
    "Portland-Vancouver-Hillsboro, OR-WA",
    "San Francisco-Oakland-Berkeley, CA",
    "San Jose-Sunnyvale-Santa Clara, CA",
    "Los Angeles-Long Beach-Anaheim, CA",
    "San Diego-Chula Vista-Carlsbad, CA",
    "Phoenix-Mesa-Chandler, AZ",
    "Las Vegas-Henderson-Paradise, NV",
    "Denver-Aurora-Lakewood, CO",
    "Salt Lake City, UT",
    "Kansas City, MO-KS",
    "St. Louis, MO-IL",
    "Minneapolis-St. Paul-Bloomington, MN-WI",
    "Dallas-Fort Worth-Arlington, TX",
    "Houston-The Woodlands-Sugar Land, TX",
    "San Antonio-New Braunfels, TX",
    "Austin-Round Rock-Georgetown, TX",
    "Chicago-Naperville-Elgin, IL-IN-WI",
    "Milwaukee-Waukesha, WI",
    "Indianapolis-Carmel-Anderson, IN",
    "Columbus, OH",
    "Cincinnati, OH-KY-IN",
    "Cleveland-Elyria, OH",
    "Detroit-Warren-Dearborn, MI",
    "Boston-Cambridge-Newton, MA-NH",
    "New York-Newark-Jersey City, NY-NJ-PA",
    "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",
    "Washington-Arlington-Alexandria, DC-VA-MD-WV",
    "Baltimore-Columbia-Towson, MD",
    "Atlanta-Sandy Springs-Alpharetta, GA",
    "Miami-Fort Lauderdale-Pompano Beach, FL",
    "Tampa-St. Petersburg-Clearwater, FL",
    "Orlando-Kissimmee-Sanford, FL"
  ],
  gsa: [
    "Pacific Northwest GSA",
    "Northern California GSA",
    "Southern California GSA",
    "Southwest GSA",
    "Mountain GSA",
    "Great Plains GSA",
    "Central GSA",
    "South GSA",
    "Texas GSA",
    "Midwest GSA",
    "Great Lakes GSA",
    "Mid-Atlantic GSA",
    "Northeast GSA",
    "Southeast GSA",
    "Florida GSA"
  ]
};

export const getAvailableRegions = (regionType) => {
  if (regionType === 'all' || !regionHierarchy[regionType]) return [];
  return regionHierarchy[regionType];
};


